name: Deploy Cloud Function
run-name: ${{ github.actor }} triggered deploy pipeline

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      tag_version:
        required: true
        type: string

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL}}"
  SLACK_CHANNEL: "${{ secrets.GITHUBACTIONS_SLACK_CHANNEL }}"

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v3"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: Deploy to Cloud Functions
        uses: actions-hub/gcloud@540.0.0
        id: deploy
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          SERVICE_NAME: "${{ secrets.SERVICE_NAME }}"
          SERVICE_REGION: "${{ secrets.SERVICE_REGION }}"
        with:
          args: functions deploy '${{ env.SERVICE_NAME }}' --source='${{ secrets.BUCKET_PATH }}/${{ secrets.ARCHIVE_NAME }}-${{ github.event.inputs.tag_version }}.zip' --region='${{ env.SERVICE_REGION }}' --project='${{ env.PROJECT_ID }}' --runtime=nodejs24 --gen2 --trigger-http

      - name: Run Notification
        id: runnotificationsent
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: ${{ secrets.GITHUBACTIONS_SLACK_CHANNEL  }}
          message: Deploying {{ env.GITHUB_REF_NAME }} branch ${{ job.status }}
        if: always()
