name: Build Cloud Function
run-name: ${{ github.actor }} triggered deploy pipeline

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      chart_path:
        required: true
        type: string

jobs:
  build:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Read version
        id: getversion
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"

          echo "Current branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == release/* ]]; then
            # Extract version from release branch name
            VERSION="${BRANCH_NAME#release/}"
            VERSION="${VERSION#v}"   # strip leading v if present
            echo "Detected release branch. Version: $VERSION"
          else
            # Extract version from Helm chart
            VERSION=$(awk -F'"' '/^appVersion:/ {print $2}' "${{ inputs.chart_path }}")
            echo "Detected non-release branch. Version from chart: $VERSION"
          fi

          if [ -z "$VERSION" ]; then
            echo "ERROR: Version could not be determined"
            exit 1
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          project_id: "${{ secrets.PROJECT_ID }}"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: "Set up Cloud SDK"
        id: setupsdk
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: Zip the application
        id: zipapplication
        run: |
          ARCHIVE="${{ secrets.ARCHIVE_NAME }}-${{ steps.getversion.outputs.version }}.zip"
          echo "archive=$ARCHIVE" >> "$GITHUB_OUTPUT"
          rm -f "$ARCHIVE"
          zip -r "$ARCHIVE" .

      - name: Use gcloud CLI to upload the source to the bucket
        run: |
          gsutil -h x-goog-meta-github-sha:${{ github.sha }} cp "${{ steps.zipapplication.outputs.archive }}" '${{ secrets.BUCKET_PATH }}'
