name: Semantic Release Workflow

on:
  workflow_call:
    inputs:
      chart_path:
        required: true
        type: string
      environments:
        required: false
        type: string
        default: ""
      docker_tags:
        required: false
        type: boolean
        default: true
    secrets:
      PROJECT_ID:
        required: true
      GAR_LOCATION:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      SLACK_CHANNEL:
        required: true
      DEPLOY_APP_ID:
        required: true
      DEPLOY_APP_PRIVATE_KEY:
        required: true
      WIF_PROVIDER:
        required: true
      WIF_SERVICE_ACCOUNT:
        required: true

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: ${{ secrets.GITHUBACTIONS_SLACK_CHANNEL }}
  NODE_VERSION: 20

jobs:
  semantic:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate GitHub App token
        id: gh-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
          owner: HDRUK
          repositories: |
            ${{ github.event.repository.name }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.gh-token.outputs.token }}

      - name: Read version from Helm chart
        id: getversion
        run: |
          VERSION=$(awk -F'"' '/^appVersion:/ {print $2}' ${{ inputs.chart_path }})
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Merge changes from main to dev (squash)
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
          RELEASE_VERSION: ${{ steps.getversion.outputs.version }}
        run: |
          git fetch origin dev
          git checkout dev
          git merge --squash origin/main || true
          git checkout --theirs . || true
          git add .
          git commit --allow-empty -m \
            "sync: update dev from main (release ${RELEASE_VERSION}) [skip ci]"
          git push origin dev

  build:
    name: Build and Push Release Image
    needs: semantic
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    strategy:
      matrix:
        environment: ${{ fromJson(inputs.environments != '' && format('["{0}"]', inputs.environments) || '["release"]') }}

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Read appVersion
        id: getversion
        run: |
          VERSION=$(awk -F'"' '/^appVersion:/ {print $2}' ${{ inputs.chart_path }})
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.PROJECT_ID }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
