name: 'Terraform Manual Workflow'

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      branch:
        required: true
        type: string
      step_to_run:
        required: true
        type: string
      target_resource:
        required: false
        type: string

env:
  PROJECT_ID: '${{ secrets.PROJECT_ID }}'
  ENV: '${{ secrets.ENV }}'
  TF_ACTIONS_WORKING_DIR: '${{ secrets.TF_ACTIONS_WORKING_DIR }}'
  GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: '${{ inputs.env }}'

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: '${{ env.TF_ACTIONS_WORKING_DIR }}'
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.branch}}
            
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v3'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' 
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init

      run: |-
        git config --global url."https://outh2:${{ secrets.GH_TOKEN }}@github.com".insteadOf https://github.com
        terraform init -reconfigure

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      if: ${{ inputs.step_to_run == 'plan' }}
      run: terraform plan -input=false

    # Deploy the infrastructure
    - name: Terraform Apply
      if: ${{ inputs.step_to_run == 'apply' }}
      run: terraform apply -auto-approve -input=false

    # Deploy the targeted infrastructure
    - name: Targeted Apply Targeted
      if: ${{ inputs.step_to_run == 'targeted-apply' }} 
      run: terraform apply -target="${{ inputs.target_resource }}"